### ISSUE TITLE
EDIutils 0.0.0.9000

### ISSUE THREAD

**Issue by clnsmth** [sccoos/HABsDataPublish#1]
Hey @BrennieDev,

EDIutils has undergone a major refactor for submission to rOpenSci and CRAN. This new and improved version covers the full data repository REST API, handles authentication more securely, better matches API call and result syntax, improves documentation, and opens the door for development of wrapper functions to support common data management tasks. In the process of this refactor the function names and call patterns have changed and several functions supporting other EDI R packages have been removed, thereby creating back compatibility breaking changes with the previous major release (version 1.6.1). The previous version will be available until 2022-06-01 on the `deprecated` branch. Install the previous version with: 
  
```
remotes::install_github("EDIorg/EDIutils", ref = "deprecated")
```

EDIutils functions used in your code and the suggested replacement call:

- REPLACE: `api_list_data_package_revisions()` WITH: `list_data_package_revisions()`
- REPLACE: `api_update_data_package()` WITH: `update_data_package()`, `check_status_update()`, and `read_data_package_report_summary()`

Please let me know if you have any questions, 
@clnsmth

**Comment by ianbrunjes** [comment]
Hi @clnsmth -

Thanks for letting me know about this, and for identifying what needs to be updated! Really very much appreciated! I'll let you know if I have any questions when I update it.

**Comment by ianbrunjes** [comment]
@clnsmth I know EDIutils is being/has been submitted to CRAN. Wondering if there is any known timeline for when we might be able to expect it there?

**Comment by clnsmth** [comment]
Hi @BrennieDev. EDIutils will be submitted to CRAN this week and should be up a week or so after.

**Comment by clnsmth** [comment]
@BrennieDev EDIutils was just now submitted to CRAN. I'll send an update when it's accepted.

**Comment by ianbrunjes** [comment]
Awesome news! Thanks for the update @clnsmth!

**Comment by clnsmth** [comment]
@BrennieDev EDIutils is now on CRAN : )
https://cran.r-project.org/web/packages/EDIutils/index.html

**Comment by ianbrunjes** [comment]
Updated! Many thanks for the continued help with this, @clnsmth
